kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: exam
data:
  default.conf: |
    server {
        listen 80 default_server;
        index index.php index.html;
        server_name _;
        root /var/www/html;

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }