apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            defaultMode: 420
        - name: shared-files
          emptyDir: {}
      containers:
        - name: molnar-php-exam
          image: gmlnar/molnar-php-exam:latest
          imagePullPolicy: Always
          command:
            - /usr/local/sbin/php-fpm
            - '--force-stderr'
            - '--nodaemonize'
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /var/www/app/. /var/www/html"]
        - name: nginx
          image: library/nginx:1.20.1
          imagePullPolicy: Always
          command:
            - /usr/sbin/nginx
            - '-g'
            - daemon off;
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - '-s'
                  - quit
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-files
              mountPath: /var/www/html
