kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: exam
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31531
  selector:
    app: nginx
  type: NodePort